### ISSUE TITLE
Error in samples/process-document.v1beta3.js

### ISSUE THREAD

**Issue by PabloPerezAguilo** [googleapis/nodejs-document-ai#134]
With `node samples/process-document.v1beta3.js` I got this error:

```javascript
{ Error: 3 INVALID_ARGUMENT: Request contains an invalid argument.
    at Object.callErrorFromStatus (/home/info/cloudshell_open/nodejs-document-ai/samples/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/info/cloudshell_open/nodejs-document-ai/samples/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/home/info/cloudshell_open/nodejs-document-ai/samples/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
    at Object.onReceiveStatus (/home/info/cloudshell_open/nodejs-document-ai/samples/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at process.nextTick (/home/info/cloudshell_open/nodejs-document-ai/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 3,
  details: 'Request contains an invalid argument.',
  metadata:
   Metadata {
     internalRepr: Map { 'grpc-server-stats-bin' => [Array] },
     options: {} },
  note:
   'Exception occurred in retry method that was not classified as transient' }
```
I had the same error in localhost and CloudShell. 

Im using a service account in json format: `export GOOGLE_APPLICATION_CREDENTIALS="[PATH]"`

![image](https://user-images.githubusercontent.com/9373112/100264327-f9cf5080-2f4e-11eb-8c10-19bf66f27155.png)

**Comment by gishan** [comment]
I have the same issue, any solution?

**Comment by gishan** [comment]
I got the answer 

```
const {
  DocumentProcessorServiceClient,
} = require('@google-cloud/documentai').v1beta3;
const client = new DocumentProcessorServiceClient({
  apiEndpoint: 'us-documentai.googleapis.com',
});
```
you have to add the apiEndPoint

**Comment by PabloPerezAguilo** [comment]
It works for me with EU server:

`const client = new DocumentProcessorServiceClient({
    apiEndpoint: 'eu-documentai.googleapis.com',
});`
